version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - python -m pip install --upgrade --no-cache-dir sphinxcontrib-bibtex 4s

sphinx:
  configuration: docs/source/conf.py
