version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install uv
      - uv sync --only-group docs

sphinx:
  configuration: docs/source/conf.py
